root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "swag init --parseDependency --parseInternal --dir ./src && go build -o ./tmp/main ./src/main.go "
  delay = 1000 # Delay in milliseconds (1 second) between builds
  exclude_dir = ["assets", "tmp", "vendor"] # Ignoring directories that don't need watching
  exclude_file = []
  exclude_regex = []
  follow_symlink = false
  full_bin = "" # Empty, meaning it'll use the default `bin`
  include_dir = ["src"] # Limit to the source directory to avoid infinite looping
  include_ext = ["go"] # Watch only Go files for changes
  kill_delay = "1s" # Provide a small kill delay for smoother termination
  log = "build-errors.log"
  send_interrupt = true # Use interrupt signals for graceful stops
  stop_on_error = true # Stop build process if an error occurs

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
