services:
  dine-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8080:8080"
    volumes:
      - go-modules:/go/pkg/mod
    # depends_on:
    #   - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
      - ENVIRONMENT=testing
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_AGE=${ACCESS_TOKEN_AGE}
      - REFRESH_TOKEN_AGE=${REFRESH_TOKEN_AGE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}

  # postgres:
  #   image: postgres:15-alpine
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #     - ./migrations:/docker-entrypoint-initdb.d
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}

  #   ports:
  #     - "${POSTGRES_PORT}:5432"

volumes:
  # postgres-data:
  go-modules:
