definitions:
  main.Response:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  models.LoginUserData:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.RegisterUserData:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Health check endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Response'
      summary: Health check endpoint
      tags:
      - Health
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login a user in the system
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.LoginUserData'
      produces:
      - application/json
      responses: {}
      summary: Login a user
      tags:
      - Auth
  /api/v1/auth/logout:
    post:
      description: Clear user authentication cookies
      produces:
      - application/json
      responses: {}
      summary: Logout a user
      tags:
      - Auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Generate a new access token using a refresh token
      parameters:
      - description: Refresh Token
        in: header
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Refresh Access Token
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user in the system
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.RegisterUserData'
      produces:
      - application/json
      responses: {}
      summary: Create a new user
      tags:
      - Auth
  /api/v1/users:
    get:
      description: Get all users in the system, or a specific user if the user_id
        query parameter is provided
      parameters:
      - description: User ID to filter by
        in: query
        name: user_id
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get all users or a specific user by ID
      tags:
      - Users
swagger: "2.0"
